# NUMPY BASICS

PYTHON PROGRAMMING
 

This Notebook will cover the following topics:

1.Numpy basics 

2.Built-in methods and functions 

3.Obtain shape, length and type of Numpy arrays 

4.Reshape 

5.Minimum and maximum and their indices 

6.Mathematical Operations 

7.Indexing and slicing 

8.mSelection 

# NUMPY BASICS

NumPy is a Linear Algebra Library used for multidimensional arrays
Installation: Use the command window, type: conda install numpy

In [2]:
import numpy as np

In [3]:
list1 = [5,9,4]     # one dimensional array
list1

[5, 9, 4]

In [4]:
y= np.array(list1)    # array
y

array([5, 9, 4])

In [5]:
type(list1)

list

In [6]:
list2 = np.array([[1,5],[6,8]])     # multidimensional array
list2                               # matrix

array([[1, 5],
       [6, 8]])

# Built in Methods and Functions

In [8]:
x = np.random.rand(10)    # rand() use for distribution between 0 and 1
x

array([0.32983963, 0.25201094, 0.48502926, 0.40802392, 0.25305145,
       0.41240925, 0.07845495, 0.9351332 , 0.41263102, 0.48000931])

In [8]:
y = np.random.randint(1,10)    # randint is used to generate integers
y

6

In [9]:
x = np.random.randint(1,100,15)
x

array([11, 28, 96, 85, 87, 13, 62, 37, 22, 66,  5, 29, 68, 26, 15])

In [10]:
x = np.arange(1,50)    # arange in order
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
x = np.arange(1,50,5)   # intrval of 5
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [12]:
x = np.eye(5)    # matrix (5x5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# array of ones

x=np.ones(15)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
# array of matrices of ones

x = np.ones((15,15))    # (r x c)
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

# Shape , Length and Type of numpy arrays

In [15]:
# get length

len(x)

15

In [16]:
# get shape

x.shape

(15, 15)

In [17]:
list2.shape

(2, 2)

In [18]:
# get datatype

x.dtype

dtype('float64')

# Reshape

In [19]:
y = np.array([3,5,7,9])
y.reshape(2,2)              # convert array to matrix (2x2)

array([[3, 5],
       [7, 9]])

# Max and Min values and their index

In [25]:
y.max()    # max value

9

In [20]:
y.min()    # min value

3

In [21]:
y.argmax()   # index of max value

3

In [22]:
y.argmin()   # index of min value

0

# Mathematical Operations

In [23]:
x=np.arange(1,5)
x

array([1, 2, 3, 4])

In [24]:
y=np.arange(1,5)
z=x+y
z

array([2, 4, 6, 8])

In [25]:
z=x**2    # squarng x
z

array([ 1,  4,  9, 16], dtype=int32)

In [26]:
k=np.sqrt(z)    #sq.rt
k

array([1., 2., 3., 4.])

In [28]:
z=np.exp(y)    #exponent
z

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# Elements slicing and indxing

In [29]:
x=np.random.randint(1,10,10)
x

array([2, 8, 4, 3, 5, 5, 5, 6, 6, 3])

In [30]:
x[3]    #3rd index value

3

In [32]:
x[0:3]    #[start:stop(-1)]

array([2, 8, 4])

In [33]:
# broadcasting, altering several values in numpy array at ones

x[0:6]=10
x

array([10, 10, 10, 10, 10, 10,  5,  6,  6,  3])

In [34]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[8, 6, 9, 5, 9],
       [3, 3, 6, 5, 4],
       [5, 8, 7, 7, 8],
       [4, 2, 8, 4, 3],
       [2, 2, 2, 5, 3]])

In [35]:
# get row from matrix

matrix[2]

array([5, 8, 7, 7, 8])

In [36]:
# get element

matrix[0][2]

9

In [38]:
mini = matrix[:3]    # [:3] = [0:3] sorting first 3 rows
mini

array([[8, 6, 9, 5, 9],
       [3, 3, 6, 5, 4],
       [5, 8, 7, 7, 8]])

In [40]:
mini = matrix[2:]    # [2:last] = [2:4] sorting last 3 rows
mini

array([[5, 8, 7, 7, 8],
       [4, 2, 8, 4, 3],
       [2, 2, 2, 5, 3]])

In [43]:
mini = matrix [:,:2]    # [:,0:2] first 2 columns
mini

array([[8, 6],
       [3, 3],
       [5, 8],
       [4, 2],
       [2, 2]])

In [45]:
mini = matrix [:,2:]    # [:,2:last] last 3 columns
mini

array([[9, 5, 9],
       [6, 5, 4],
       [7, 7, 8],
       [8, 4, 3],
       [2, 5, 3]])

# Elements Selection

In [46]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[6, 3, 5, 3, 4],
       [6, 4, 5, 8, 5],
       [6, 2, 1, 6, 8],
       [1, 4, 1, 5, 4],
       [7, 1, 8, 5, 5]])

In [48]:
new = matrix[matrix>3]    # get numbers more then 3
new

array([6, 5, 4, 6, 4, 5, 8, 5, 6, 6, 8, 4, 5, 4, 7, 8, 5, 5])

# NumPy Arrays


python objects:

high-level number objects: integers, floating point

containers: lists (costless insertion and append), dictionaries (fast lookup)
 

Numpy provides:

extension package to Python for multi-dimensional arrays

closer to hardware (efficiency)

designed for scientific computation (convenience)

Also known as array oriented computin

In [49]:
import numpy as np

a= np.array([0,1,2,3])
print(a)
print (np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [50]:
# list comp

a= list(range(1,100,3))
a

[1,
 4,
 7,
 10,
 13,
 16,
 19,
 22,
 25,
 28,
 31,
 34,
 37,
 40,
 43,
 46,
 49,
 52,
 55,
 58,
 61,
 64,
 67,
 70,
 73,
 76,
 79,
 82,
 85,
 88,
 91,
 94,
 97]

In [52]:
ans = []
for i in a:
    if i%2==0:        # even numbers
        ans.append(i)
ans

[4, 10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94]

In [54]:
# method 2

[i for i in a if i%2==0]

[4, 10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94]

In [56]:
[i**2 for i in range(1,10)]    # square of numbers between 1 to 10

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [57]:
# python list

L = range(1000)
%timeit [i**2 for i in L]

264 µs ± 13.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [58]:
a = np.arange(1000)
%timeit a**2

1.22 µs ± 36.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Creating Array

In [59]:
# 1-d

a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [60]:
# print Dimensions

a.ndim

1

In [61]:
# shape

a.shape

(4,)

In [62]:
# length

len(a)

4

In [63]:
# 2-D , 3-D

b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
b.ndim

2

In [65]:
b.shape

(2, 3)

In [66]:
len(b)

2

In [68]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])   # matrix
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [69]:
c.ndim

3

# functions for creatng arrays

In [70]:
# using array fn

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [72]:
# using linspace

a= np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [73]:
# array using dig fn

a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [74]:
# extract diagional

np.diag(a)

array([1, 2, 3, 4])

In [75]:
# array using random
# uniform distribution

a = np.random.rand(4)
a

array([0.96480877, 0.78967489, 0.97477159, 0.34754914])

In [76]:
# standard normal distribution / Gausian

a = np.random.randn(4)
a

array([-0.08452446, -0.40663596,  0.25081477, -1.41278583])